services:
    database:
        image: postgres:16-alpine
        container_name: database
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
            interval: 5s
            timeout: 3s
            retries: 5
        networks:
            - internal
            - external
        ports:
            - "6666:5432"
        volumes:
            - db-data:/var/lib/postgresql/data
    
    redis:
        image: redis:8.4-alpine
        container_name: redis
        networks:
            - internal
            - external
        ports:
            -   "6379:6379"
        volumes:
            -   redis-data:/data
        healthcheck:
            test: ["CMD-SHELL", "redis-cli", "-a", "ping"]
            interval: 5s
            timeout: 3s
            retries: 5
    
    shortener:
        build:
            context: ./Shortener/
            dockerfile: ./Dockerfile
        container_name: shortener
        environment:
            - ASPNETCORE_URLS=https://*:7000;http://*:5000
            - ASPNETCORE_Kestrel__Certificates__Default__Path=${CERT_PATH}
            - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PASSWORD}
            - ConnectionStrings__DefaultConnection=Host=${DB_HOST};Port=5432;Username=${DB_USER};Password=${DB_PASSWORD};Database=${DB_NAME}
            - ConnectionStrings__Redis=redis:6379
        depends_on:
            database:
                condition: service_healthy
        networks:
            - internal
            - external
        ports:
            - "5000:5000"
            - "7000:7000"
        volumes:
            - ./certificates:/https:ro
    
    shortener.web.ui:
        build:
            context: ./Shortener.WebUI
            dockerfile: ./Dockerfile
        container_name: shortener.web.ui
        environment:
            - ASPNETCORE_URLS=https://*:7001;http://*:5001
            - ASPNETCORE_Kestrel__Certificates__Default__Path=${CERT_PATH}
            - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PASSWORD}
        depends_on:
            database:
                condition: service_healthy
        networks:
            - internal
            - external
        ports:
            - "5001:5001"
            - "7001:7001"
        volumes:
            -   ./certificates:/https:ro

networks:
    internal:
        driver: bridge
        internal: true
    external:
        driver: bridge

volumes:
    db-data:
    redis-data:
